### ISSUE TITLE
CameraX ML KIT giving error " java.lang.IllegalStateException: Image is already closed

### ISSUE THREAD

**Issue by atarana** [rmtmckenzie/flutter_qr_mobile_vision#200]

**Comment by dtodt** [comment]
Hi! I'm facing this problem too, any idea when this fix would be available?

Error log:
```sh
I/cgr.qrmv.QrReader(20606): Using new camera API.
I/cgr.qrmv.QrCameraC2(20606): Device target size: 1080x2448
I/cgr.qrmv.QrCameraC2(20606): Camera sensor flipped: true
I/cgr.qrmv.QrCameraC2(20606): Set preview size: 3264x1400
I/cgr.qrmv.QrCameraC2(20606): Set camera size: 3264x1400
I/cgr.qrmv.QrCameraC2(20606): Setting af mode to: 3
I/NDOP    (20606): listening using window listener
W/cgr.qrmv.QrDetector(20606): Barcode Reading Failure:
W/cgr.qrmv.QrDetector(20606): com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.0.0:9)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.0.0:2)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.0.0:4)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.0.0:1)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
W/cgr.qrmv.QrDetector(20606): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/cgr.qrmv.QrDetector(20606): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.0.0:2)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
W/cgr.qrmv.QrDetector(20606): 	at java.lang.Thread.run(Thread.java:923)
W/cgr.qrmv.QrDetector(20606): Caused by: java.lang.IllegalStateException: Image is already closed
W/cgr.qrmv.QrDetector(20606): 	at android.media.Image.throwISEIfImageIsInvalid(Image.java:71)
W/cgr.qrmv.QrDetector(20606): 	at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:909)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.common.zzb.zzb(com.google.mlkit:vision-common@@17.0.0:1)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.common.InputImage.getPlanes(com.google.mlkit:vision-common@@17.0.0:1)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.barcode.internal.zzl.zza(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:7)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.barcode.internal.zzi.zzc(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:3)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.barcode.internal.zzi.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:1)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@17.0.0:2)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
W/cgr.qrmv.QrDetector(20606): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.0.0:8)
W/cgr.qrmv.QrDetector(20606): 	... 10 more
```

```
Android version: 11
qr_mobile_vision: ^4.0.1
```
