### ISSUE TITLE
Failed assertion previewDetails is null

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#21]
On a phone in 4.2.2 I have this error 

```
V/Provider/Settings( 8162): invalidate [system]: current 13 != cached 12
V/Provider/Settings( 8162): from db cache, name = sound_effects_enabled , value = 0
I/SurfaceTextureClient( 8162): [STC::queueBuffer] (this:0x554be010) fps:4.90, dur:6734.60, max:5847.55, min:10.42
I/SurfaceTextureClient( 8162): [STC::queueBuffer] this:0x554be010, api:1, last queue time elapsed:5847.55
I/BufferQueue( 8162): [unnamed-8162-2](this:0x55902d40,api:0) BufferQueue
I/BufferQueue( 8162): [unnamed-8162-2](this:0x55902d40,api:0) consumerConnect
I/BufferQueue( 8162): [unnamed-8162-2](this:0x55902d40,api:0) setConsumerName: unnamed-8162-2
I/SurfaceTexture( 8162): [unnamed-8162-2](this:0x5616a708,api:0) SurfaceTexture
I/SurfaceTexture( 8162): [unnamed-8162-2](this:0x5616a708,api:0) detachFromContext
I/System.out( 8162): Making detector for formats: 0
W/DynamiteModule( 8162): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
D/ActivityThread( 8162): installProvider: context=android.app.ContextImpl@40f67c30holder=android.app.IActivityManager$ContentProviderHolder@40fcb4c8noisy=truenoReleaseNeeded=falsestable=false
I/DynamiteModule( 8162): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 8162): Cannot load feature, fall back to load whole module.
W/DynamiteModule( 8162): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 8162): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
I/DynamiteModule( 8162): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702
D/ActivityThread( 8162): getPackageInfo: securityViolation=true
I/Vision  ( 8162): Loading library libbarhopper.so
I/Vision  ( 8162): libbarhopper.so library load status: true
E/Camera  ( 8162): fengke getCameraInfo1
E/Camera  ( 8162): fengke getCameraInfo2 cameraInfo.mCamSensorID = 113
D/Camera-JNI( 8162): (tid:8162)[MtkJNICameraContext] this:0x56ef3fa8 camera->getStrongCount(3) 
E/Camera  ( 8162): fengke getCameraInfo1
E/Camera  ( 8162): fengke getCameraInfo2 cameraInfo.mCamSensorID = 113
I/Camera  ( 8162): Camera framework getParameters =afeng-max-focus-step=0;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz;auto-exposure-lock-supported=false;auto-whitebalance-lock-supported=false;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,continuousshot,smileshot,autorama;capfname=/sdcard/DCIM/cap00;effect=none;effect-values=none,mono,negative,sepia,sepiablue;exposure-compensation=0;exposure-compensation-step=1.0;fb-sharp=0;fb-sharp-max=4;fb-sharp-min=-4;fb-skin-color=0;fb-skin-color-max=4;fb-skin-color-min=-4;fb-smooth-level=0;fb-smooth-level-max=4;fb-smooth-level-min=-4;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-mode=infinity;focus-mode-values=infinity;horizontal-view-angle=63;iso-speed=auto;iso-speed-values=auto;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,320x240;jpeg-thumbnail-width=160;max-exposure-compensation=1;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=0;max-zoom=10;min-exposure-compensation=-1;mtk-cam-mode=0;picture-format=jpeg;picture-format-values=jpeg;picture-size=640x480;picture-size-values=176x144,320x240,640x480,600x400,1200x800,1024x768,1680x1120,1600x1200;preferred-preview-size-for-video=480x320;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=15,30;preview-size=320x240;preview-size-values=176x144,320x240,352x288,384x288,480x320;rotation=0;scene-mode=auto;scene-mode-values=auto,night,hdr;smooth-zoom-supported=true;vertical-view-angle=49;video-frame-format=yuv420i-yyuvyy-3plane;video-size=320x240;video-size-values=176x144,320x240,480x320,640x480,600x400;video-stabilization=false;video-stabilization-supported=false;whitebalance=auto;whitebalance-values=auto,incandescent,daylight,cloudy-daylight,fluorescent,tungsten;zoom=0;zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;zoom-supported=true;zsd-mode=off;zsd-mode-values=off,on
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): Failed to handle method call
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.StackTraceElement;@41063990
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.startingFailed(QrMobileVisionPlugin.java:145)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.continueStarting(QRReader.java:113)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.start(QRReader.java:92)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onMethodCall(QrMobileVisionPlugin.java:92)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at android.os.MessageQueue.next(MessageQueue.java:128)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at android.os.Looper.loop(Looper.java:151)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at android.app.ActivityThread.main(ActivityThread.java:5400)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision( 8162): 	at dalvik.system.NativeStart.main(Native Method)
I/flutter ( 8162): CashRegisterModeChangedAction  = CashRegisterMode.scan
I/flutter ( 8162): 1
I/flutter ( 8162): Another exception was thrown: 'package:qr_mobile_vision/qr_camera.dart': Failed assertion: line 115 pos 16: 'previewDetails != null': is not true.
```

Any idea why ?

**Comment by rmtmckenzie** [comment]
Well part of the issue is that I should really fix the errors that get propagated to flutter. I'll push a new build out soon that will fix that. As it stands, an exception is being caught but not being passed to flutter properly so we can't see what the actual exception was.

That being said, generally there are two things that would cause it to fail. 
1. play services are too old.
2. no connection to internet. 

Play services need to be relatively recent or they won't contain the right stuff for the vision library. And a dynamic module might need to be downloaded the first time for the vision to work - that's why you need internet.

**Comment by rmtmckenzie** [comment]
New build has been pushed, 0.0.3, that should at least propagate the error through to flutter so we can see what happened.

**Comment by jaumard** [comment]
Thanks ! I'll test that tomorrow (I'm not at the office today so don't have the device with me) I'll report back to you the problem. I notice an old play service on the device so I update to the latest possible (don't remember if I restart after ^^)

**Comment by jaumard** [comment]
So the real error is that: 

```
Camera  (30646): fengke getCameraInfo1
E/Camera  (30646): fengke getCameraInfo2 cameraInfo.mCamSensorID = 113
D/Camera-JNI(30646): (tid:30646)[MtkJNICameraContext] this:0x598bee50 camera->getStrongCount(3) 
E/Camera  (30646): fengke getCameraInfo1
E/Camera  (30646): fengke getCameraInfo2 cameraInfo.mCamSensorID = 113
I/Camera  (30646): Camera framework getParameters =afeng-max-focus-step=0;afeng-min-focus-step=0;antibanding=off;antibanding-values=off,50hz,60hz;auto-exposure-lock-supported=false;auto-whitebalance-lock-supported=false;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,continuousshot,smileshot,autorama;capfname=/sdcard/DCIM/cap00;effect=none;effect-values=none,mono,negative,sepia,sepiablue;exposure-compensation=0;exposure-compensation-step=1.0;fb-sharp=0;fb-sharp-max=4;fb-sharp-min=-4;fb-skin-color=0;fb-skin-color-max=4;fb-skin-color-min=-4;fb-smooth-level=0;fb-smooth-level-max=4;fb-smooth-level-min=-4;focal-length=3.5;focus-distances=0.95,1.9,Infinity;focus-mode=infinity;focus-mode-values=infinity;horizontal-view-angle=63;iso-speed=auto;iso-speed-values=auto;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x128,320x240;jpeg-thumbnail-width=160;max-exposure-compensation=1;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=0;max-num-metering-areas=0;max-zoom=10;min-exposure-compensation=-1;mtk-cam-mode=0;picture-format=jpeg;picture-format-values=jpeg;picture-size=640x480;picture-size-values=176x144,320x240,640x480,600x400,1200x800,1024x768,1680x1120,1600x1200;preferred-preview-size-for-video=480x320;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=15,30;preview-size=320x240;preview-size-values=176x144,320x240,352x288,384x288,480x320;rotation=0;scene-mode=auto;scene-mode-values=auto,night,hdr;smooth-zoom-supported=true;vertical-view-angle=49;video-frame-format=yuv420i-yyuvyy-3plane;video-size=320x240;video-size-values=176x144,320x240,480x320,640x480,600x400;video-stabilization=false;video-stabilization-supported=false;whitebalance=auto;whitebalance-values=auto,incandescent,daylight,cloudy-daylight,fluorescent,tungsten;zoom=0;zoom-ratios=100,114,132,151,174,200,229,263,303,348,400;zoom-supported=true;zsd-mode=off;zsd-mode-values=off,on
W/c.g.r.QrMobVisPlugin(30646): Starting QR Mobile Vision failed
W/c.g.r.QrMobVisPlugin(30646): java.lang.RuntimeException: setParameters failed
W/c.g.r.QrMobVisPlugin(30646): 	at android.hardware.Camera.native_setParameters(Native Method)
W/c.g.r.QrMobVisPlugin(30646): 	at android.hardware.Camera.setParameters(Camera.java:2030)
W/c.g.r.QrMobVisPlugin(30646): 	at com.github.rmtmckenzie.qrmobilevision.QrCameraC1.start(QrCameraC1.java:44)
W/c.g.r.QrMobVisPlugin(30646): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.continueStarting(QRReader.java:101)
W/c.g.r.QrMobVisPlugin(30646): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.start(QRReader.java:83)
W/c.g.r.QrMobVisPlugin(30646): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onMethodCall(QrMobileVisionPlugin.java:92)
W/c.g.r.QrMobVisPlugin(30646): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
W/c.g.r.QrMobVisPlugin(30646): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
W/c.g.r.QrMobVisPlugin(30646): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/c.g.r.QrMobVisPlugin(30646): 	at android.os.MessageQueue.next(MessageQueue.java:128)
W/c.g.r.QrMobVisPlugin(30646): 	at android.os.Looper.loop(Looper.java:151)
W/c.g.r.QrMobVisPlugin(30646): 	at android.app.ActivityThread.main(ActivityThread.java:5400)
W/c.g.r.QrMobVisPlugin(30646): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/c.g.r.QrMobVisPlugin(30646): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/c.g.r.QrMobVisPlugin(30646): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
W/c.g.r.QrMobVisPlugin(30646): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
W/c.g.r.QrMobVisPlugin(30646): 	at dalvik.system.NativeStart.main(Native Method)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): Failed to handle method call
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.String;@410c6bf8
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.startingFailed(QrMobileVisionPlugin.java:153)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.continueStarting(QRReader.java:104)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.start(QRReader.java:83)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onMethodCall(QrMobileVisionPlugin.java:92)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at android.os.MessageQueue.next(MessageQueue.java:128)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at android.os.Looper.loop(Looper.java:151)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at android.app.ActivityThread.main(ActivityThread.java:5400)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
E/MethodChannel#com.github.rmtmckenzie/qr_mobile_vision(30646): 	at dalvik.system.NativeStart.main(Native Method)
I/flutter (30646): CashRegisterModeChangedAction  = CashRegisterMode.scan
I/flutter (30646): 1
I/flutter (30646): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30646): The following assertion was thrown building FutureBuilder<PreviewDetails>(dirty, state:
I/flutter (30646): _FutureBuilderState<PreviewDetails>#28888):
I/flutter (30646): 'package:qr_mobile_vision/qr_camera.dart': Failed assertion: line 115 pos 16: 'previewDetails !=
I/flutter (30646): null': is not true.
I/flutter (30646): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30646): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30646): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30646):   https://github.com/flutter/flutter/issues/new
I/flutter (30646): When the exception was thrown, this was the stack:
I/flutter (30646): #2      new Preview (package:qr_mobile_vision/qr_camera.dart)
I/flutter (30646): #3      QrCameraState.build.<anonymous closure>.<anonymous closure> (package:qr_mobile_vision/qr_camera.dart:74:32)
I/flutter (30646): #4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter (30646): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter (30646): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (30646): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (30646): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (30646): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (30646): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (30646): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (30646): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (30646): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (30646): #14     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (30646): #15     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (30646): (elided 2 frames from class _AssertionError)
```

**Comment by jaumard** [comment]
Apparently you try to set a parameter to the camera that is not supported by the device I test on

**Comment by rmtmckenzie** [comment]
Which device is this btw? I assume that it doesn't have auto-focus and that's why it's failing.

**Comment by rmtmckenzie** [comment]
The newest version should fix this by trying first with autofocus, then if that fails tries without autofocus. Try v0.0.5 once it's done processing.

**Comment by jaumard** [comment]
I'm not at the office today so I can't test until next week, but thanks a lot :) I'll test and let you know which device it is. But it's an old shity device lol

**Comment by jaumard** [comment]
@rmtmckenzie instead of retrying if it fails, isn't it better to first try to check if auto focus is present or not on the device and use it or not depending on this (https://stackoverflow.com/questions/4368564/android-check-whether-camera-supports-auto-focus) didn't check your implementation yet so I don't know if it's doable but look more clean if it is

**Comment by rmtmckenzie** [comment]
I've updated to do as you suggested, for both camera1 and camera2 api's now.
