### ISSUE TITLE
Add ability to scan once instead of multiple times

### ISSUE THREAD

**Issue by HectorV12** [rmtmckenzie/flutter_qr_mobile_vision#55]
Great Work on this package! very helpful, thanks.
I have this issue,
I have this :
```
qrCodeCallback: (code) {
        var route = MaterialPageRoute(
          builder: (BuildContext context) => ProductDetails(
                productCode: code,
              ),
        );
        return Navigator.of(context).push(route);
      }
```
and it builds too many pages.
Also, is there a specific example on how to work with the QrCameraState as the GlobalKey? a bit confused on that part.

**Comment by rmtmckenzie** [comment]
I'm eventually going to do a refactor to split the logic of the view and the controller, and when I do I'll probably put in an option to stop after the first item.

But for now you're probably better off just using a member variable and setting it to true once you've scanned the item, then ignoring it in the callback.

Note that you don't have to do setState as you're not changing anything that affects the build funciton.


i.e.
```dart
class QrScannerState extends State<QrScanner> {

  bool hasScanned = false;

  qrCodeCallback: (code) {
    if (hasScanned) return;
    hasScanned = true;
    ......
  }
}
```

And if you actually want to stop/start the camera using GlobalKey, this is how you'd do it. I haven't included it in the answer as it's actually a pretty messy way of doing things and I'd like to replace it as soon as I get time.

```dart
class QrScannerState extends State<QrScanner> {
  GlobalKey<QrCameraState> qrCameraKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return ....
      ...
      QrCamera(
        key: qrCameraKey,
        qrCodeCallback: (code) async {
          qrCameraKey.currentState.stop();
          ...
        }
      ...
  }
}
```

**Comment by rmtmckenzie** [comment]
I'll keep this issue open for now as a reminder for when I do the refactoring.

**Comment by HectorV12** [comment]
Appreciate the help, thanks again!

**Comment by HectorV12** [comment]
Thanks for your help again !
Maybe you can help with this issue, possibly related to this package:
So the package worked the way I want it to but when I added an unpublished package for the flashlight, turning on the flashlight freezes the QrCamera.

Unpublished package: 
[torch.zip](https://github.com/rmtmckenzie/flutter_qr_mobile_vision/files/2697017/torch.zip)

error:
```
E/CameraCaptureSession(21623): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(21623): android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): checkPidStatus:1536: The camera device has been disconnected
E/CameraCaptureSession(21623): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:707)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1006)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:390)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:568)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:233)
E/CameraCaptureSession(21623): 	at android.os.Handler.handleCallback(Handler.java:789)
E/CameraCaptureSession(21623): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraCaptureSession(21623): 	at android.os.Looper.loop(Looper.java:164)
E/CameraCaptureSession(21623): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/CameraCaptureSession(21623): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(21623): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/CameraCaptureSession(21623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/CameraCaptureSession(21623): Caused by: android.os.ServiceSpecificException: checkPidStatus:1536: The camera device has been disconnected (code 4)
E/CameraCaptureSession(21623): 	at android.os.Parcel.readException(Parcel.java:1981)
E/CameraCaptureSession(21623): 	at android.os.Parcel.readException(Parcel.java:1913)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:375)
E/CameraCaptureSession(21623): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)
E/CameraCaptureSession(21623): 	... 11 more
E/BufferItemConsumer(21623): [ImageReader-640x480f23m2-21623-0] Failed to release buffer: Unknown error -1 (1)
```

and if I added `qrCameraKey.currentState.restart();` to the flashlight function, the QrCamera flickers and restarts but the flashlight turns off

onPressed Flashlight function:
```
Future _turnFlash() async {
    hasScanned = false;
    qrCameraKey.currentState.restart();
    _isOn ? await Torch.flashOff : await Torch.flashOn;
    setState(() {
      _isOn = !_isOn;
    });
  }
```

error:
```
I/cgr.qrmv.QrReader(23620): Using new camera API.
I/cgr.qrmv.QrDetector(23620): Making detector2 for formats: 512
W/DynamiteModule(23620): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule(23620): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle(23620): Cannot load feature, fall back to load whole module.
W/DynamiteModule(23620): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(23620): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(23620): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
I/Vision  (23620): Loading library libbarhopper.so
I/Vision  (23620): libbarhopper.so library load status: true
I/CameraManager(23620): getCameraCharacteristics : cameraId = 0
I/chatty  (23620): uid=10320(u0_a320) com.example.chadenn identical 1 line
I/CameraManager(23620): getCameraCharacteristics : cameraId = 0
E/Camera  (23620): Error 2
V/Surface (23620): sf_framedrop debug : 0x4f4c, game : false, logging : 0
V/Surface (23620): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/cgr.qrmv.QrCameraC2(23620): Setting af mode to: 4
I/zygote64(23620): Do full code cache collection, code=123KB, data=87KB
I/zygote64(23620): After code cache collection, code=119KB, data=71KB
I/zygote64(23620): Do partial code cache collection, code=123KB, data=79KB
I/zygote64(23620): After code cache collection, code=123KB, data=79KB
I/zygote64(23620): Increasing code cache capacity to 512KB
I/zygote64(23620): Background concurrent copying GC freed 874(159KB) AllocSpace objects, 28(8MB) LOS objects, 49% free, 11MB/23MB, paused 2.056ms total 167.805ms
I/zygote64(23620): Background concurrent copying GC freed 1203(142KB) AllocSpace objects, 44(14MB) LOS objects, 50% free, 11MB/23MB, paused 4.938ms total 105.347ms
D/ViewRootImpl@dd8cade[MainActivity](23620): ViewPostIme pointer 0
D/ViewRootImpl@dd8cade[MainActivity](23620): ViewPostIme pointer 1
I/System.out(23620): Failed to get camera : java.lang.RuntimeException: getParameters failed (empty parameters)

```
Any help is appreciated, thanks!
